version: '3.9'

services:
  api:
    build:
      context: ./backend/api
      dockerfile: Dockerfile
    container_name: voxify_api
    depends_on:
      - db-init
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development  # change to 'production' for production use
      - DATABASE_URL=sqlite:///data/voxify.db
      - VECTOR_DB_PATH=data/chroma_db
    volumes:
      - ./backend:/app
      - data_volume:/app/data
    restart: unless-stopped
    command: flask run --host=0.0.0.0

  db-init:
    build:
      context: ./backend/database
      dockerfile: Dockerfile
    container_name: voxify_db_init
    volumes:
      - ./backend:/app
      - data_volume:/app/data
    environment:
      - DATABASE_URL=sqlite:///data/voxify.db
      - VECTOR_DB_PATH=data/chroma_db
    entrypoint: ["python3", "database/init_db.py"]
    restart: "no"

  ai:
    build:
      context: ./ai
      dockerfile: Dockerfile
    container_name: voxify_ai
    ports:
      - "6000:6000"
    environment:
      - MODEL_CACHE=/models
    volumes:
      - ./ai:/app
      - model_cache:/models
    restart: unless-stopped

volumes:
  data_volume:
  model_cache: