name: Voxify CI

on:
  push:
    branches [ main ]
  pull_request:
    branches [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install flake8 and black
        run: |
          pip install flake8 black

      - name: Run flake8
        run: |
          flake8 app/backend/api app/backend/scripts app/backend/tests

      - name: Run black (check mode)
        run: |
          black --check app/backend/api app/backend/scripts app/backend/tests
          
  docker-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        run:
          docker-compose -f app/backend/docker-compose.yml build

      - name: Run DB init
        run: |
          docker-compose -f app/backend/docker-compose.yml run --rm db-init

      - name: Run tests
        run: |
          docker-compose -f app/backend/docker-compose.yml run --rm tests

      - name: Shut down services
        run: docker-compose -f app/backend/docker-compose.yml down --volumes