name: Voxify CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build base image
        run: docker build -f backend/Dockerfile.base -t backend-base:latest backend
      
      - name: Build all services
        run: docker-compose build
      
      - name: Run backend linting
        run: docker-compose run --rm lint-backend
      
      - name: Run frontend linting
        run: docker-compose run --rm lint-frontend
      
      - name: Initialize database
        run: docker-compose run --rm db-init
      
      - name: Start API and run tests
        run: |
          docker-compose up -d api
          echo "Waiting for API to start..."
          sleep 10
          docker-compose run --rm tests
      
      - name: Shut down services
        run: docker-compose down --volumes