name: Voxify CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Free up disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          docker system prune -af
          df -h
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build base image
        run: |
          docker build -f backend/Dockerfile.base -t backend-base:latest backend
          docker tag backend-base:latest backend-base:latest
      
      - name: Build services
        run: |
          docker compose build lint-backend
          docker system prune -f
          docker compose build db-init  
          docker system prune -f
          docker compose build api
          docker system prune -f
          docker compose build frontend
          docker compose build tests
      
      - name: Run backend linting
        run: docker compose run --rm lint-backend
      
      - name: Run frontend linting
        run: docker compose run --rm lint-frontend
      
      - name: Initialize database
        run: docker compose run --rm db-init
      
      - name: Start API and run tests
        run: |
          docker compose up -d api
          echo "Waiting for API to start..."
          sleep 10
          docker compose run --rm tests
      
      - name: Shut down services
        run: docker compose down --volumes